blank_issues_enabled: false
contact_links:
  - name: Questions, Sharing ideas, Other support
    url: https://github.com/meza/auth0-remix-server/discussions
    about: Check out the community discussions.
